FROM ubuntu

RUN apt-get -y update && echo '2022-03-11'
RUN apt-get -y install software-properties-common && add-apt-repository ppa:ondrej/php && apt-get update

#
# PHP
#
RUN apt-get -y install php8.0
RUN apt-get -y install php8.0-mysql
RUN apt-get -y install php8.0-xml
RUN apt-get -y install php8.0-mbstring
RUN apt-get -y install php8.0-curl
RUN apt-get -y install php8.0-sqlite3

#
# Install required packages
#
RUN apt-get -y install zip unzip curl

#
# Code Coverage
#
RUN apt-get -y install php8.0-xdebug
RUN echo xdebug.mode=coverage >> /etc/php/8.0/cli/conf.d/20-xdebug.ini

#
# Install composer
#
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php --install-dir=/usr/local/bin  --filename=composer && \
php -r "unlink('composer-setup.php');"

#
# Install node js
#
RUN cd /tmp && curl https://nodejs.org/dist/v17.7.1/node-v17.7.1-linux-x64.tar.gz -O
RUN tar -xzf /tmp/node-v17.7.1-linux-x64.tar.gz -C /usr/local/
ENV PATH "${PATH}:/usr/local/node-v17.7.1-linux-x64/bin/"
RUN npm install yarn -g

#
# Apache modules
#
RUN cd /etc/apache2/mods-enabled && ln -s ../mods-available/rewrite.load
